---
- name: Run the clevis-script.sh through expect
  delegate_to: "{{ groups['tang-server'][0] }}"
  shell: |
    set timeout 5
    spawn bash /tmp/clevis.sh
    expect -re "(.*)ynYN(.*)"
    send "y\n"
    expect eof
    exit 0
  args:
    executable: /usr/bin/expect
  register: clevis_output

- name: Set a temporary fact with the key
  set_fact:
    secret_key: "{{ clevis_output.stdout_lines[3] }}"

- name: build items list
  set_fact:
    tang_keys: "{{tang_keys|default([]) + [{item: {'key': secret_key }}] }}"
