---
- when:
    - inventory_hostname in groups['tang-server']
    - use_tang is defined and use_tang | bool
  block:
    - name: Install expect package
      delegate_to: "{{ groups['tang-server'][0] }}"
      package:
        name: "{{ package }}"
        state: present
      loop_control:
        loop_var: package
      loop:
        - expect
        - tang
        - clevis

    - name: Create clevis script
      delegate_to: "{{ groups['tang-server'][0] }}"
      copy:
        dest: /tmp/clevis.sh
        content: |
          echo $(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w ${1:-32} | head -n 1) | clevis-encrypt-tang '{"url":"{{ tang_url }}"}'
