apiVersion: v1
kind: Service
metadata:
  annotations:
    egressip-ipam-operator.redhat-cop.io/keepalivedgroup: egressip-ipam-operator/keepalivedgroup-router
  name: router-default
  namespace: openshift-ingress
spec:
  externalIPs: 
  - "192.168.131.129"
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: metrics
    port: 1936
    protocol: TCP
    targetPort: 1936
  selector:
    ingresscontroller.operator.openshift.io/deployment-ingresscontroller: default
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}