- name: list all VMs
  virt:
    command: list_vms
  register: all_vm
  become: true  

- name: stop bootstrap
  virt:
    state: destroyed
    name: '{{ item.name }}.{{ cluster.compute.vms_domain }}'
  with_items:
  - '{{ cluster.compute.bootstrap }}'
  when: (item.name~'.'~cluster.compute.vms_domain) in all_vm.list_vms
  become: true

- name: stop masters
  virt:
    state: destroyed
    name: '{{ item.name }}.{{ cluster.compute.vms_domain }}'
  with_items: '{{ cluster.compute.masters }}'
  when: item.name~'.'~cluster.compute.vms_domain in all_vm.list_vms
  become: true  
  
- name: stop workers
  virt:
    state: destroyed
    name: '{{ item.name }}.{{ cluster.compute.vms_domain }}'
  with_items: '{{ cluster.compute.workers }}'
  when: item.name~'.'~cluster.compute.vms_domain in all_vm.list_vms
  become: true  

- name: undefine bootstrap
  virt:
    command: undefine
    name: '{{ item.name }}.{{ cluster.compute.vms_domain }}'
  with_items:
  - '{{ cluster.compute.bootstrap }}'
  when: item.name~'.'~cluster.compute.vms_domain in all_vm.list_vms
  become: true  

- name: undefine masters
  virt:
    command: undefine
    name: '{{ item.name }}.{{ cluster.compute.vms_domain }}'
  with_items: '{{ cluster.compute.masters }}'
  when: item.name~'.'~cluster.compute.vms_domain in all_vm.list_vms
  become: true  
  
- name: undefine workers
  virt:
    command: undefine
    name: '{{ item.name }}.{{ cluster.compute.vms_domain }}'
  with_items: '{{ cluster.compute.workers }}'
  when: item.name~'.'~cluster.compute.vms_domain in all_vm.list_vms
  become: true
  
- name: remove bootstrap's image
  file:
    path: "{{ item.image_file_name }}"
    state: absent
  with_items:
  - '{{ cluster.compute.bootstrap }}'

- name: remove master's images
  file:
    path: "{{ item.image_file_name }}"
    state: absent
  with_items: '{{ cluster.compute.masters }}'
  
- name: remove worker's images
  file:
    path: "{{ item.image_file_name }}"
    state: absent
  with_items: '{{ cluster.compute.workers }}'    