   

- name: create ignition
  command: openshift-install create ignition-configs --dir {{ workdir.install }}

- name: adjust permissions
  file: 
    path: "{{ workdir.install }}/bootstrap.ign"
    state: file
    setype: virt_content_t
    mode: 0644

- name: adjust permissions
  file: 
    path: "{{ workdir.install }}/master.ign"
    state: file
    setype: virt_content_t
    mode: 0644    


- name: adjust permissions
  file: 
    path: "{{ workdir.install }}/worker.ign"
    state: file
    setype: virt_content_t  
    mode: 0644
  