- name: stop network
  virt_net:
    state: inactive
    name: '{{ install_config.metadata.name }}'
  become: true    

- name: undefine network
  virt_net:
    command: undefine
    name: '{{ install_config.metadata.name }}' 
  become: true    