- hosts: localhost
  roles:
  - role: prerequisites

- hosts: localhost
  roles:
  - role: configure-client-dns

- hosts: localhost
  roles:
  - role: create-network  

- hosts: localhost
  roles:
  - role: create-ignition
  
- hosts: localhost
  roles:
  - role: create-vms

- hosts: localhost
  roles:
  - role: remove-bootstrap

- hosts: localhost
  roles:
  - role: add-workers  