- hosts: localhost
  roles:
  - role: prerequisites

- hosts: localhost
  roles:
  - role: configure-client-dns  

- hosts: localhost
  roles:
  - role: create-network  

- hosts: localhost
  roles:
  - role: create-registry-mirror  