
base_image_name: rhcos-410.8.20190604.0-qemu.qcow2
baseImageURL: https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/ootpa/410.8.20190604.0/rhcos-410.8.20190604.0-qemu.qcow2

workdir:
  vm_data: /home/rspazzol/git/ocp4-ansible-libvirt/vms
  install: /home/rspazzol/git/ocp4-ansible-libvirt/install

cluster:
  compute:
    vms_domain: vms.{{ install_config.metadata.name }}.{{ install_config.baseDomain }}
    bootstrap:
      name: bootstrap
      ip: '192.168.131.10'
      mac: '52:54:00:2c:01:10'
      memory: 8192
      cpus: 2
      image_file_name: "{{ workdir.vm_data }}/bootstrap.qcow2"
      ign_file_name: "{{ workdir.install }}/bootstrap.ign"
    masters:
    - name: master-1
      ip: '192.168.131.11'
      mac: '52:54:00:2c:01:11'      
      memory: 16384
      cpus: 4
      image_file_name: "{{ workdir.vm_data }}/master-1.qcow2"
      ign_file_name: "{{ workdir.install }}/master.ign"
    workers: []
    # - name: worker-1
    #   ip: '192.168.131.12'
    #   mac: '52:54:00:2c:01:12
    #   memory: 8192
    #   cpus: 2
    #   image_file_name: "{{ workdir.vm_data }}/worker-1.qcow2"
    #   ign_file_name: "{{ workdir.install }}/worker.ign"      
  network:
    dhcp:
      min: 192.168.131.10
      max: 192.168.131.254
    bridge:
      default_route: 192.168.131.1
      mac:  52:54:00:2c:01:00
      netmask: '255.255.255.0'
    
install_config:
  apiVersion: v1
  baseDomain: mylaptop.io
  compute:
  - hyperthreading: Enabled
    name: worker
    platform: {}
    replicas: 0
  controlPlane:
    hyperthreading: Enabled
    name: master
    platform: {}
    replicas: 1
  metadata:
    name: ocp4-libvirt
  platform:
    none: {}  
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    machineCIDR: 10.0.0.0/16
    networkType: OpenShiftSDN
    serviceNetwork:
    - 172.30.0.0/16
#  pullSecret: "{{ lookup('file', lookup('env','PULL_SECRET_FILE')) | quote }}"
#  sshKey: "{{ lookup('file', lookup('env','PUBLIC_SSH_KEY_FILE')) }}"